target:	gtushell BuNeDu pwd lsf cat wc

gtushell:	gtushell.c 
		gcc gtushell.c -o gtushell -std=gnu99

BuNeDu:	BuNeDu.c 
		gcc BuNeDu.c -o BuNeDu -std=gnu99

pwd:	pwd.c 
		gcc pwd.c -o pwd -std=gnu99

lsf:	lsf.c 
		gcc lsf.c -o lsf -std=gnu99
		
cat:	cat.c 
		gcc cat.c -o cat -std=gnu99	

wc:		wc.c 
		gcc wc.c -o wc -std=gnu99	

clean:
		rm gtushell BuNeDu pwd lsf cat wc
